name: build-docker-api-user

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build-docker-api-user.yml'
    - 'udagram-api-user'

env:
  APPLICATION_NAME: udagram-api-user

jobs:
  build-docker-image:
    name: Build and Publish a Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.APPLICATION_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{ env.APPLICATION_NAME }}
      
    - name: Build
      run: docker build . -t ${{ env.APPLICATION_NAME }}

    - name: Tag
      run: docker tag ${{ env.APPLICATION_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:latest

    - name: Publish
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}